<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="Créer un bouton de partage personnalisé pour Facebook - karac blog" />
    <meta property="og:image" content="https://karac.ch/storage/articles/August2017/pJBVDQrp5BpNriveaDZg.jpg" />
    <meta property="og:description" content="Dans ce tutoriel, nous allons voir comment ajouter à votre site un joli bouton de partage personnalisé pour Facebook (le fonctionnement est le même pour les autres réseaux sociaux)." />
    <meta property="og:url" content="https://karac.ch/blog/bouton_partage_personnalise">
    <title><?= $article->title ?></title>
    <link rel="stylesheet" href="bootstrap.min.css" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="css/article.css">
  </head>
  <body>
    <!-- En-tête commune de l'application -->
     <?php include('layout/navbar.phtml'); ?>
    <div class="row">
      <div class="col-md-8"></div>
      <div class="col-md-4 ">
        <form class="form-inline " action="resultat.php" method="POST">
          <input class="form-control col-md-9" type="search" name="title" placeholder="Search" aria-label="Search">
          <button class="btn btn-info col-md-3 pt-2 pb-2" type="submit"><i class="fas fa-search"></i> Search</button>
        </form>
      </div>
    </div>
    <br>
    <div class="row mt-4 text-right mb-5 mr-5">
      <div class="col-md-12">
        <a href="index.php" class="btn btn-info mb-3"><b><i class="fas fa-hand-point-left"></i> Acceuil</b></a>
      </div>
    </div>
    <div style="background-color: #00000080" class="container shadow p-3 mb-5  rounded pl-4 pr-2 pr-3" >
      <div class="row">
        <h2 ><b><?= $article->title ?></b></h2>
      </div>
      <div class="row">
        <div class="col-md-6 mb-2">
          <img style="border: 2px solid #13B3EBFF" class="w-100 rounded"  src="<?= $article->image ?>">
        </div>
        <div class="col-md-6">
          <p  style="color: grey"><b><i class="fas fa-pen-alt"></i> Publié par:</b> <span style="color: #55AA00FF"><b><?= $users->firstname.' '.$users->lastname ?></b></span></p>
          <p style="color: grey"><b><i class="fas fa-clock"></i> Publié le:</b> <time style="color: #55AA00FF"><?= $article->date ?></time></p>
          <p style="color: grey"><b><i class="fas fa-bookmark"></i> Catégorie: <span style="color: #55AA00FF"><?= $article->name ?></span></b></p>
          <a href="https://www.facebook.com/sharer/sharer.php?u=http://localhost/blog/article.php?id=<?= $article->id ?>" class="sharebox btn btn-info" target="blank">
            <span class="fb-icon"></span><b><i class="fab fa-facebook"></b></i> partager</b></a>
          </div>
          <div class=" divider"></div>
          <br>
          <div class="col-md-12  ">
            <p style="color: #A6585DFF"><b><i class="fas fa-scroll"></i> Description:</b></p>
            <p class="row text-white"><?= $article->content ?>  </p>
          </div>
          <div class="col-md-12  ">
            <p style="color: #A6585DFF"><b><i class="fas fa-video"></i> Vidéo à propos: <?= $article->title ?> </b></p>
            <iframe style="border:3px solid white " class="w-100 rounded" width="560" height="500" src="<?php echo $article->video ?>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
        </div>
      </div>
      <br>
      <div style="background-color: #FCFCFCFD" class="container shadow p-3 mb-5 rounded pl-4 pr-2 ">
        <h3 class="row" style="color:#20B9DEFF"><b><i class="fas fa-comments"></i> Commentaires:</b> </h3>
        <?php foreach ($nombre as $nbr): ?>
        <p class="h3 text-info"><b><i class="fas fa-comments-dollar"></i> Il existe <span class="text-danger"> <?php echo $nbr->nombrecomm; ?></span> commentaires pour cet article</b></p>
        <?php endforeach ?>
      </div>
      <div style="background-color: #FCFCFCFD" class="container shadow p-3 mb-5 rounded pl-4 pr-2 " id="houss">
        <?php foreach ($comments as $com): ?>
        <!--<a class="btn btn-danger btn-sm float-right" href="removeComment.php?id=<?=$com->id?>&article=<?=$article->id?>"><i class="fas fa-trash-alt"></i></a>-->
        <hr>
        <h4 class="row" style="color: #F75107FF"><i class="fas fa-user-edit"></i> <?= $com->author ?></h4>
        <time><i class="fas fa-clock"></i> Le <?= $com->date ?></time>
        <br><br>
        <div class="row">
          <p class="col-md-12"><i class="fas fa-quote-right"></i> <?= $com->comment ?></p>
        </div>
        <hr>
        <?php endforeach; ?>
      </div>
      <hr>
      <div style="background-color: #FFFFFF80" class="container shadow p-3 mb-5 rounded pl-4 pr-2 ">
        <?php if (isset($success))
        echo "<p style='color:green; font-size:1.3em;'><b>".$success."<b/></p>";
        if (!empty($errors)):?>
        <?php foreach ($errors as $error): ?>
        <div class="row">
          <div class="col-md-3"></div>
          <div class="col-md-6">
            <div class="alert alert-danger"><?= $error ?></div>
          </div>
        </div>
        <?php endforeach; ?>
        
        <?php endif; ?>
        <div class="row">
          <div class="col-md-3"></div>
          <fieldset class="col-md-6 pt-3 pb-3" >
            <legend style="color: #303030FF"><b><i class="fas fa-comment"></i> Nouveau commentaire</b></legend>
            <form id="comments-form"  method="POST" >
              <p><label for="author"><b>pseudo:</b> </label><br>
              <input type="text" name="author" id="author" value="<?php if(isset($author)) echo $author ?>" class="form-control"></p>
              <p id="pserr"  style="font-style: italic;color:red"></p>
              <p><label for="comment"><b>Commentaire:</b> </label><br>
            <textarea name="comment" id="comment" cols="30" rows="5" class="form-control"><?php if(isset($comment)) echo $comment ?></textarea></p>
            <input type="hidden" name="id" value="<?= $article->id ?>">
            <p id="cmerr" style="font-style: italic;color:red"></p>
            <div class="row">
              <div class="col-md-3"></div>
              <button id="publier" type="submit" class="col-md-2 btn btn-success mb-2 mr-1 ml-1"><b>Publier</b></button>
              <div class="col-md-2"></div>
              <button id="reset" class="col-md-2 btn btn-danger mb-2 mr-1 ml-1" type="reset"><b>Annuler</b></button>
            </div>
            <div class="row thx">
              <div class="col-md-2"></div>
            </div>
          </form>
        </fieldset>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3"></div>
      <p class=" h2 mt-3 pt-2 pb-2 text-white col-md-2 bg-dark rounded text-center"><b><i class="fas fa-newspaper"></i> Autre articles</b></p>
    </div>
    
    <div class="row">
      <div class="col-md-3"></div>
    <div class="pr-4 pl-4 col-md-6 ">
      <div class="bd-example w-100">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <?php $i=0; foreach ($random as $alt): ?>
            <div class="carousel-item <?php if($i==0) { echo 'active'; }; $i++; ?>" >
              <img class="w-100" style="height: 450px; border:4px solid grey" src="<?= $alt->image ?>" class="d-block img-thumbnail">
              <div style="background-color: #000000DE" class="carousel-caption  d-md-block">
                <h4><b><i class="fas fa-newspaper"></i> <?= $alt->title?></b></h4>
                <?php foreach ($user as $value): ?>
                <p  style="color: grey"><b><i class="fas fa-pen-alt"></i> Publié par:</b> <span style="color: #55AA00FF"><b><?= $value->firstname.' '.$value->lastname ?></b></span></p>
                <?php endforeach; ?>
                <time><span style="color: grey"><i class="fas fa-clock"></i> Le </span><?= $alt->date ?></time>
                <p><b><span style="color: #A0A0A0FF"><i class="fas fa-bookmark"></i> Catégorie:</span> <span style="color: #55AA00FF"><?= $alt->name ?></span></b></p>
                <a href="article.php?id=<?= $alt->id ?>" class="btn btn-primary" ><b>Voir l'article</b></a>
                <a href="https://www.facebook.com/sharer/sharer.php?u=http://localhost/blog/article.php?id=<?= $alt->id ?>" class="sharebox btn btn-info" target="blank">
                  <span class="fb-icon"></span><b><i class="fab fa-facebook"></b></i> partager</b></a>
                </div>
              </div>
              <?php endforeach ?>
            </div>
            
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
      </div>
      </div>
      <div class="row mt-4 text-center mb-5">
        <div class="col-md-12">
          <a href="index.php" class="btn btn-info "><b><i class="fas fa-hand-point-left"></i> Acceuil</b></a>
        </div>
      </div>
      <footer>
        <div class="container-fluid footer mt-2">
          <div class="row licence">
            <div class="col-md-12">
              <h3><i class="far fa-copyright"></i><b>Blog Houssem Eddine Mabrouk 2019</b></h3>
              <div class="fr">
                <div style="display: inline-block;">
                  <input class="col-md-6 fEmail" name='Email' placeholder='Entrer ton Email'/>
                  <a href="#" class="subS">S'inscrire</a>
                </div>
              </div>
            </div>
            <div class="soc col-md-12">
              <ul>
                <li class="soc1"><a href="https://www.linkedin.com/in/houssem-eddine-mabrouk-619456138/"target="_blank"></a></li>
                <li class="soc2"><a href="https://www.facebook.com/houssem.sahiliano"target="_blank"></a></li>
                <li class="soc3"><a href="https://twitter.com/twitter"target="_blank"></a></li>
                <li class="soc4"><a href="https://www.instagram.com/houssem_mbrr"target="_blank"></a></li>
                <li class="soc5"><a href="https://3wa.fr/"target="_blank"></a></li>
                <li class="soc6"><a href="https://www.youtube.com/channel/UCOTiomQKUi-Oc1IPnhS0woQ?view_as=subscriber"target="_blank"></a></li>
                <li class="soc7"><a href="mailto:houssemeddinemabrouk@gmail.com"target="_blank"></a></li>
                <li class="soc8"><a href="https://dribbble.com/Houssem-mbr"target="_blank"></a></li>
              </ul>
            </div>
          </div>
          <div class="text-right mr-5">
            <a  id="tp" style="font-size: 3em;color: #FF0E00FF; cursor: pointer;" ><i class="fas fa-arrow-circle-up"></i></a>
          </div>
        </div>
      </footer>
      <script src="jquery-3.4.0.slim.min.js"></script>
      <script type="text/javascript" src="js/comment.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script>
      $(document).ready(function(){
      // Add smooth scrolling to all links
      $("#tp").on('click', function(event) {
      // Make sure this.hash has a value before overriding default behavior
      if (this.header !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();
      // Store hash
      var header = this.header;
      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
      scrollTop: $('header').offset().top
      }, 2000, function(){
      // Add hash (#) to URL when done scrolling (default click behavior)
      window.location.header = header;
      });
      } // End if
      });
      });
      !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
      $(function() {
      $('#comments-form').submit(function (e) {

      e.preventDefault();//Enlever les comportement par défaut lorsque chui en formulaire
      $('#pserr').empty();//A chaque fois je veux soumettre tout le formulaire remet à zero (message d'erreur...)
      $('#cmerr').empty();
      var postdata = $('#comments-form').serialize();
      var auth = $('#author').val();
      var comm = $('#comment').val();

      if (auth == "") {
        $('#pserr').html("T'as oublier votre pseudo !!");
        return;
      }
      if (comm == ""){
        $('#cmerr').html("T'as oublier de mettre votre commentaire !!");
        return;
      }
      var data=$('#houss');
      //chercher tout les infos dans le formulaire et les mettre dans une variable postdata
      //------------------------------
      //Ajax
      //------------------------------
      $.ajax({
      type: 'POST',//type d'information
      url: 'addComments.php',//de la quelle on va récupérer les informations
      data: postdata,
      dataType: 'json',
      success: function(result){
      if (result) {
      //est-ce que le resultat envoyer par php est valider (isSuccess=true et il n'ya pas des eurreurs)
      //$('.thx').append("<p class='thank-you col-md-10' style='color: green;'>Votre commentaire a bien été publier.<i class='far fa-smile-beam'></i></p>");
      console.log(result);
           data.empty();
            $('#author').empty();
            $('#comment').empty();
      $.each(result,function(index, value) {

      data.append('<hr><h4 class="row" style="color: #F75107FF"><i class="fas fa-user-edit"></i>'+value.author+'</h4><time><i class="fas fa-clock"></i> Le '+value.date+'</time><br><br><div class="row"><p class="col-md-12"><i class="fas fa-quote-right"></i>'+value.comment+'</p></div><hr>')
       

      
      });
      
      }
      }
      });
      });
      });
      </script>
    </body>
  </html>