<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="Créer un bouton de partage personnalisé pour Facebook - karac blog" />
    <meta property="og:image" content="https://karac.ch/storage/articles/August2017/pJBVDQrp5BpNriveaDZg.jpg" />
    <meta property="og:description" content="Dans ce tutoriel, nous allons voir comment ajouter à votre site un joli bouton de partage personnalisé pour Facebook (le fonctionnement est le même pour les autres réseaux sociaux)." />
    <meta property="og:url" content="https://karac.ch/blog/bouton_partage_personnalise">
    <title>Catégorie</title>
    <link rel="stylesheet" href="bootstrap.min.css" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="css/article.css">
  </head>
  <body>
    <?php include('layout/navbar.phtml'); ?>
      <div class="row">
      <div class="col-md-8"></div>
      <div class="col-md-4 ">
        <form class="form-inline " action="resultat.php" method="POST">
          <input class="form-control col-md-9" type="search" name="title" placeholder="Search" aria-label="Search">
          <button class="btn btn-info col-md-3 pt-2 pb-2" type="submit"><i class="fas fa-search"></i> Search</button>
        </form>
      </div>
    </div>
    <br>
     <div class="row mt-4 text-right mb-5 mr-5">
      <div class="col-md-12">
        <a href="index.php" class="btn btn-info mb-3"><b><i class="fas fa-hand-point-left"></i> Acceuil</b></a>
      </div>
    </div>
    <div class="container text-center rounded-circle bg-info">
      <?php foreach ($onecatecory as $value): ?>
      <h1 class="pt-2 pb-3" style="color: white"><b><i class="fas fa-bookmark"></i> <?php echo $value->name ;?></b> </h1>
      <p class="h2 text-white pb-2">Nombre d'articles:<b> <span class="text-warning"><b> <?php echo $value->n ; ?></b></span></p>
      <?php endforeach; ?>
    </div>
    <br><br>
    <div class="row text-center">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <?php foreach ($category as $value): ?>
        <a href="getCategory.php?id=<?php echo $value->id?>"><button class="btn btn-danger ml-2 mb-2"><b><?php echo $value->name; ?></b></button></a>
        <?php endforeach; ?>
      </div>
      <div class="col-md-3"></div>
    </div>
    <hr>
    <div class="container-fluid">
      <div style="max-width:1900px; margin:auto;" class="row">
        <div class="col-md-9 d-inline">
          <div class="container">
            <div class="row text-center ">
              <?php foreach ($articles as $article): ?>
              
              <div style="background-color: #00000080" class="shadow-lg p-3 mb-5  rounded col-md-4" style="width: 18rem;">
                <img style="width: 300px;height: 200px" class="img-thumbnail" src="<?= $article->image?>" class="card-img-top">
                <div class="card-body">
                  <h4 class="card-title"><b><i class="fas fa-newspaper"></i> <?= $article->title?></b></h4>
                  <?php foreach ($user as $value): ?>
                  <p  style="color: grey"><b><i class="fas fa-pen-alt"></i> Publié par:</b> <span style="color: #55AA00FF"><b><?= $value->firstname.' '.$value->lastname ?></b></span></p>
                  <?php  endforeach; ?>
                  <time><span style="color: grey"><i class="fas fa-clock"></i> Le </span><?= $article->date ?></time>
                  <p class="card-text"><b><span style="color: #A0A0A0FF"><i class="fas fa-bookmark"></i> Catégorie:</span> <span style="color: #55AA00FF"><?= $article->name ?></span></b></p>
                  <a href="article.php?id=<?= $article->id ?>" class="btn btn-primary" ><b>Voir l'article</b></a>
                  <a href="https://www.facebook.com/sharer/sharer.php?u=http://localhost/blog/article.php?id=<?= $article->id ?>" class="sharebox btn btn-info" target="blank">
                    <span class="fb-icon"></span><b><i class="fab fa-facebook"></b></i> partager</b></a>
                  </div>
                </div>
                <?php endforeach ?>
              </div>
            </div>
          </div>
          <?php include('layout/widget.phtml') ?>
            </div>
          </div>
           <div class="row mt-4 text-center mb-5 mr-5">
      <div class="col-md-12">
        <a href="index.php" class="btn btn-info mb-3"><b><i class="fas fa-hand-point-left"></i> Acceuil</b></a>
      </div>
    </div>
          <footer>
            <div class="container-fluid footer mt-2">
              <div class="row licence">
                <div class="col-md-12">
                  <h3><i class="far fa-copyright"></i><b>Blog Houssem Eddine Mabrouk 2019</b></h3>
                  <div class="fr">
                    <div style="display: inline-block;">
                      <input class="col-md-6 fEmail" name='Email' placeholder='Entrer ton Email'/>
                      <a href="#" class="subS">S'inscrire</a>
                    </div>
                  </div>
                </div>
                <div class="soc col-md-12">
                  <ul>
                    <li class="soc1"><a href="https://www.linkedin.com/in/houssem-eddine-mabrouk-619456138/"target="_blank"></a></li>
                    <li class="soc2"><a href="https://www.facebook.com/houssem.sahiliano"target="_blank"></a></li>
                    <li class="soc3"><a href="https://twitter.com/twitter"target="_blank"></a></li>
                    <li class="soc4"><a href="https://www.instagram.com/houssem_mbrr"target="_blank"></a></li>
                    <li class="soc5"><a href="https://3wa.fr/"target="_blank"></a></li>
                    <li class="soc6"><a href="https://www.youtube.com/channel/UCOTiomQKUi-Oc1IPnhS0woQ?view_as=subscriber"target="_blank"></a></li>
                    <li class="soc7"><a href="mailto:houssemeddinemabrouk@gmail.com"target="_blank"></a></li>
                    <li class="soc8"><a href="https://dribbble.com/Houssem-mbr"target="_blank"></a></li>
                  </ul>
                </div>
              </div>
              <?php include('layout/footer.phtml') ?>
        </body>
      </html>