<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="Créer un bouton de partage personnalisé pour Facebook - karac blog" />
    <meta property="og:image" content="https://karac.ch/storage/articles/August2017/pJBVDQrp5BpNriveaDZg.jpg" />
    <meta property="og:description" content="Dans ce tutoriel, nous allons voir comment ajouter à votre site un joli bouton de partage personnalisé pour Facebook (le fonctionnement est le même pour les autres réseaux sociaux)." />
    <meta property="og:url" content="https://karac.ch/blog/bouton_partage_personnalise">
    <title>blog de Houssem</title>
    <link rel="stylesheet" href="bootstrap.min.css" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="css/normalize.css">
    <link rel="stylesheet" type="text/css" href="blog.css">
  </head>
  <body>
    <div class="container-fluid bg-dark">
      <nav class="row navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="index.php"><img src="images/logo.png" alt="logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto w-100 d-flex justify-content-around align-items-center text-center">
            <li class="nav-item active">
              <a class="nav-link" href="index.php"><i class="fas fa-home"></i> Acceuil <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="posts.php"><i class="fas fa-book"></i> Tous les articles</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="contact.phtml"><i class="fas fa-phone"></i> Contactez-moi</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="propos.php"><i class="fas fa-user-tie"></i> À propos de moi</a>
              
            </li>
            <li class="nav-item">
              <a class="nav-link" href="login.php"><i class="fas fa-user-cog"></i> Administration</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <header  class="row">
      <div class="bd-example  w-100">
        <div id="carouselExampleCaptions2" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions2" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions2" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions2" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="images/header.jpg" class="d-block img-fluid w-100">
              <div class="carousel-caption d-block d-md-block">
                <h1 style="color: #01A2A6"><b><i class="fas fa-microphone"></i> ENCORE UN BLOG ?! #NOMMAISSALLO</b> </h1>
                <br><br>
                <h2 class="shadow-lg p-3 mb-5 bg-dark rounded-pill text-white"><b>Bienvenue sur le Blog Houssem Eddine Mabrouk</b></h2>
              </div>
            </div>
            <div class="carousel-item">
              <img src="images/header5-bspline.jpg" class="d-block img-fluid w-100" >
              <div class="carousel-caption  d-md-block ">
                <h1 style="color: #01A2A6"><b>Explorer et réagir mes articles !!</b></h1>
                <br><br>
                <a href="posts.php" target="blank"><button class="btn btn-success btn-lg"><b>Réagir avec mes articles</b></button></a>
              </div>
            </div>
            <div class="carousel-item">
              <img src="images/header4-lanczos3.jpg" class="d-block img-fluid w-100" >
              <div class="carousel-caption  d-md-block">
                <h1 style="color: #01A2A6">Tu veux me connaitre ??</h1>
                <br><br>
                <a href="contact.phtml"target="blank"><button class="btn btn-success btn-lg"><b>Contactez-moi</b></button></a>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleCaptions2" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleCaptions2" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <marquee class="pt-2 pb-2 text-white bg-dark border border-white" direction="right"><b><i class="fas fa-door-open"></i> Bienvenue sur mon blog je suis Mabrouk Houssem eddine un Développeur et Intégrateur Web en 3W Academy</b>
      </marquee>
      <div class="row">
      <marquee  style="height: 180px" class=" col-md-12 w-100 text-white bg-dark border border-white d-sm-inline" direction="right">
      <?php foreach ($random as $rand): ?>
      <img class=" img-thumbnail" style="height: 180px; width:280px" src="<?php echo $rand->image;?>">
      <?php endforeach ?>
      </marquee>
      </div>
    </header>
    <div class="row">
      <div class="col-md-8"></div>
      <div class="col-md-4 ">
        <form class="form-inline " action="resultat.php" method="POST">
          <input class="form-control col-md-9" type="search" name="title" placeholder="Search" aria-label="Search">
          <button class="btn btn-info col-md-3" type="submit"><i class="fas fa-search"></i> Search</button>
        </form>
      </div>
    </div>
    <hr>
    <div  class="container-fluid">
      <div  style="max-width:1900px; margin:auto;" class="row">
        <div class="col-md-9 shadow-lg p-3 rounded" style="background:url('images/bg.jpg');background-repeat: repeat;background-size: contain; ">
          <h2><b>Nos dernières articles</b></h2>
          <div class="bd-example w-100">
            <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
              </ol>
              <div class="carousel-inner">
                <?php $i=0; foreach ($latest as $late): ?>
                <div class="carousel-item <?php if($i==0) { echo 'active'; }; $i++; ?>" >
                  <img class="w-100" style="height: 500px;border: 4px solid #808080FF" src="<?= $late->image ?>" class="d-block rounded img-thumbnail">
                  <div style="background-color: #000000DE" class="carousel-caption  d-md-block">
                    <h4><b><i class="fas fa-newspaper"></i> <?= $late->title?></b></h4>
                    <?php foreach ($user as $value): ?>
                    <p  style="color: grey"><b><i class="fas fa-pen-alt"></i> Publié par:</b> <span style="color: #55AA00FF"><b><?= $value->firstname.' '.$value->lastname ?></b></span></p>
                    <?php endforeach; ?>
                    <time><span style="color: grey"><i class="fas fa-clock"></i> Le </span><?= $late->date ?></time>
                    <p><b><span style="color: #A0A0A0FF"><i class="fas fa-bookmark"></i> Catégorie:</span> <span style="color: #55AA00FF"><?= $late->name ?></span></b></p>
                    <a href="article.php?id=<?= $late->id ?>" class="btn btn-primary" ><b>Voir l'article</b></a>
                    <a href="https://www.facebook.com/sharer/sharer.php?u=http://localhost/blog/article.php?id=<?= $late->id ?>" class="sharebox btn btn-info" target="blank">
                      <span class="fb-icon"></span><b><i class="fab fa-facebook"></b></i> partager</b></a>
                    </div>
                  </div>
                  <?php endforeach ?>
                </div>
                
                <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
            </div>
            <h2 class="mt-5 mb-5"><b>Nos dernières par catégorie</b></h2>
            <div class="row ">
              <?php foreach ($latestbycat as $lat): ?>
              <div style="background-color: #FFFFFF80" class="shadow-lg p-3 mb-2  rounded col-md-6" style="width: 18rem;">
                <div class="row mb-2">
                  <p  class="card-text text-info d-inline col-md-12"><b><i class="fas fa-bookmark"></i> <?= $lat->name ?></b> <a class=" float-right btn btn-dark text-white d-inline" href="getCategory.php?id=<?php echo $lat->idcategory?>"><b><i class="fas fa-hand-point-right"></i> Voir tout</b></a></p>
                  
                 
                </div>
                <img style="height: 300px;border: 3px solid black" class="rounded w-100" src="<?= $lat->image?>" class="card-img-top">
                <div class="card-body">
                  <h4 class="card-title"><b><i class="fas fa-newspaper"></i> <?= $lat->title?></b></h4>
                  <?php foreach ($user as $value): ?>
                  <p class="text-info"><b><i class="fas fa-pen-alt"></i> Publié par:</b> <span style="color: #55AA00FF"><b><?= $value->firstname.' '.$value->lastname ?></b></span></p>
                  <?php  endforeach; ?>
                  <time><span class="text-info"><i class="fas fa-clock"></i> Le </span><?= $lat->date ?></time>
                  <br> <br>
                  <a href="article.php?id=<?= $lat->id ?>" class="btn btn-primary" ><b>Voir l'article</b></a>
                  <a href="https://www.facebook.com/sharer/sharer.php?u=http://localhost/blog/article.php?id=<?= $lat->id ?>" class="sharebox btn btn-info" target="blank">
                    <span class="fb-icon"></span><b><i class="fab fa-facebook"></b></i> partager</b></a>
                  </div>
                </div>
                <?php endforeach ?>
              </div>
              <h2 class="mt-3"><b>Articles aléatoires</b></h2>
              <div class="bd-example w-100">
                <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                  </ol>
                  <div class="carousel-inner">
                    <?php $i=0; foreach ($random as $alt): ?>
                    <div class="carousel-item <?php if($i==0) { echo 'active'; }; $i++; ?>" >
                      <img class="w-100" style="height: 450px; border:4px solid grey" src="<?= $alt->image ?>" class="d-block img-thumbnail">
                      <div style="background-color: #000000DE" class="carousel-caption  d-md-block">
                        <h4><b><i class="fas fa-newspaper"></i> <?= $alt->title?></b></h4>
                        <?php foreach ($user as $value): ?>
                        <p  style="color: grey"><b><i class="fas fa-pen-alt"></i> Publié par:</b> <span style="color: #55AA00FF"><b><?= $value->firstname.' '.$value->lastname ?></b></span></p>
                        <?php endforeach; ?>
                        <time><span style="color: grey"><i class="fas fa-clock"></i> Le </span><?= $alt->date ?></time>
                        <p><b><span style="color: #A0A0A0FF"><i class="fas fa-bookmark"></i> Catégorie:</span> <span style="color: #55AA00FF"><?= $alt->name ?></span></b></p>
                        <a href="article.php?id=<?= $alt->id ?>" class="btn btn-primary" ><b>Voir l'article</b></a>
                        <a href="https://www.facebook.com/sharer/sharer.php?u=http://localhost/blog/article.php?id=<?= $alt->id ?>" class="sharebox btn btn-info" target="blank">
                          <span class="fb-icon"></span><b><i class="fab fa-facebook"></b></i> partager</b></a>
                        </div>
                      </div>
                      <?php endforeach ?>
                    </div>
                    
                    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  </div>
                </div>
                <div>
                  <h2 class="mt-3"><b>Conseils</b></h2>
                  <iframe class="w-100" height="315" src="https://www.youtube.com/embed/3pNzdg8BWPg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
              </div>
              <?php include('layout/widget.phtml') ?>
                </div>
              </div>
              <!--<div class="row">
                <div style="height: 80px" class="col-md-1 bg-dark border border-white"><p class="h4 text-white pt-2 pl-2"><b>Nos vidéos</b></p></div>
                <marquee  style="height: 80px" class=" col-md-11 pt-2 pb-2 text-white bg-dark border border-white d-sm-inline" direction="right">
                <?php foreach ($allvid as $vi): ?>
                <iframe  width="150" height="60" src="<?php echo $vi->video ?>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <?php endforeach ?>
                </marquee>-->
              </div>
              <footer>
                <div class="container-fluid footer ">
                  <div class="row licence">
                    <div class="col-md-12">
                      <h3><i class="far fa-copyright"></i><b>Blog Houssem Eddine Mabrouk 2019</b></h3>
                      <div class="fr">
                        <div style="display: inline-block;">
                          <input class="col-md-6 fEmail" name='Email' placeholder='Entrer ton Email'/>
                          <a href="#" class="subS">S'inscrire</a>
                        </div>
                      </div>
                    </div>
                    <div class="soc col-md-12">
                      <ul>
                        <li class="soc1"><a href="https://www.linkedin.com/in/houssem-eddine-mabrouk-619456138/"target="_blank"></a></li>
                        <li class="soc2"><a href="https://www.facebook.com/houssem.sahiliano"target="_blank"></a></li>
                        <li class="soc3"><a href="https://twitter.com/twitter"target="_blank"></a></li>
                        <li class="soc4"><a href="https://www.instagram.com/houssem_mbrr"target="_blank"></a></li>
                        <li class="soc5"><a href="https://3wa.fr/"target="_blank"></a></li>
                        <li class="soc6"><a href="https://www.youtube.com/channel/UCOTiomQKUi-Oc1IPnhS0woQ?view_as=subscriber"target="_blank"></a></li>
                        <li class="soc7"><a href="mailto:houssemeddinemabrouk@gmail.com"target="_blank"></a></li>
                        <li class="soc8"><a href="https://dribbble.com/Houssem-mbr"target="_blank"></a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="text-right mr-5">
                    <a  id="tp" style="font-size: 3em;color: #FF0E00FF; cursor: pointer;" ><i class="fas fa-arrow-circle-up"></i></a>
                  </div>
                </div>
              </footer>
              <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
              <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
              <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
              <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
              <script>
              $(document).ready(function(){
              // Add smooth scrolling to all links
              $("#tp").on('click', function(event) {
              // Make sure this.hash has a value before overriding default behavior
              if (this.header !== "") {
              // Prevent default anchor click behavior
              event.preventDefault();
              // Store hash
              var header = this.header;
              // Using jQuery's animate() method to add smooth page scroll
              // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
              $('html, body').animate({
              scrollTop: $('header').offset().top
              }, 2000, function(){
              // Add hash (#) to URL when done scrolling (default click behavior)
              window.location.header = header;
              });
              } // End if
              });
              });
              !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
              </script>
            </body>
          </html>