<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Modifier un article</title>
	<link rel="stylesheet" href="bootstrap.min.css" >
 	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
 	<link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">
 	<link rel="stylesheet" type="text/css" href="css/admin.css">
</head>
<body>
	<header class="container-fluid bg-dark">
      <nav class="row navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="admin.php"><img src="images/logo.png" alt="logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto w-100 d-flex justify-content-around align-items-center text-center">
            <li class="nav-item btn btn-dark active">
              <a class="nav-link" href="admin.php"><b>Acceuil</b></a>
            </li>
            <li class="nav-item">
              <a class="nav-link btn btn-dark" href="addPosts.php"><b>Ajouter article</b></a>
            </li>
            <li class="nav-item">
              <a class="nav-link btn btn-dark" href="category.php"><b>Ajouter catégorie</b></a>
            </li>
            <li class="nav-item ">
              <a class="nav-link btn btn-dark" href="addusers.php"><b>Ajouter un admin</b></span></a>
            </li>
            <li class="nav-item ">
              <a class="nav-link btn btn-dark" href="index.php" target="blenk"><b>Vue visiteur</b></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link btn btn-warning text-white" href="login.php"><b>Déconnexion</b></a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
 	<div class="container contenu mt-3">
 		<div class="container-fluid">
 	
 		<div class=" pt-3 pb-3 pr-3 pl-3">
 			<?php if (isset($success))
 				echo "<p style='color:green; font-size:1.3em;'><b>".$success."<b/></p>";

 			if (!empty($errors)):?>

				<?php foreach ($errors as $error): ?>
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-6">
							<div class="alert alert-danger"><?= $error ?></div>
						</div>
					</div>
				<?php endforeach; ?>
 		
 	<?php endif; ?>
 	<div class="row">
 		<div class="col-md-3"></div>
 		<fieldset class="col-md-6 pt-3 pb-3" >
 			<legend class="text-info"><b><i class="fas fa-sticky-note"></i> Modifier l'article <span style="color:red"><?php  echo $article->title ?></span></b></legend>
 			<form method="POST" >
 				<p><label for="title"><b>Titre:</b> </label><br>
 				<input type="text" name="title" id="title" value="<?php  echo $article->title ?>" class="form-control"></p>
 				<p><label for="content"><b>Corps de l'article:</b> </label><br>
 				<textarea name="content" id="content" cols="30" rows="10" class="form-control"><?php echo $article->content ?></textarea></p>
        <p><label for="image"><b>Lien de l'image</b> </label><br>
        <input type="text" name="image" id="image" value="<?php  echo $article->image ?>" class="form-control"></p>
        <p><label for="title"><b>Lien youtube de video:</b> </label><br>
        <input type="text" name="video" id="video" value="<?php  echo $article->video ?>" class="form-control"></p>
 				<a style="color:green" href="category.php"><i class="fas fa-plus-circle"></i></a>
 				<select name="cat">
 					<?php foreach ($category as $value): ?>
 						<option value="<?php echo $value->id ?>" <?php if($value->id == $article->idcategory){echo "selected='selected'";} ?>><?php echo $value->name; ?></option>
 					<?php endforeach; ?>
  					
				</select>
				<select name="use">
 					<?php foreach ($user as $value): ?>
 						<option value="<?php echo $value->id ?>"><?php echo $value->firstname; ?></option>

 					<?php  endforeach; ?>
  					
				</select>
				<input type="hidden" name="id_article_mod" value="<?php echo $article->id ?>">
				<br><br>
				<div class="row">
					<div class="col-md-3"></div>
 				<button type="submit" class="col-md-2 btn btn-success mb-2 mr-1 ml-1"><b>Modifier</b></button>
 				<div class="col-md-2"></div>
               <button id="reset" class="col-md-2 btn btn-danger mb-2 mr-1 ml-1" type="reset"><b>Annuler</b></button>
               </div>
               </div>

 			</form>
 		</fieldset>	
 	</div>
	</div>
 	</div>
 		<div class="row mt-4 text-center">
 		<div class="col-md-12">
 	<a href="update.php?id=<?= $article->id ?>" class="btn btn-info"><b><i class="fas fa-hand-point-left"></i> Retour au gérer l'article</b></a>
 		</div>
 	</div>
 	</div>
 	</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>