<?php 

require_once('../config/fonction.php');
$articles= getArticles();
$latest = getLatestArticles();
$user=  getuser();
$category = getCategory();
$latestcomments = getLatestComments();
$popular = getPopularArticle();
$latestbycat = getLatestArticlesByCategory();
$random = getArticleRand();
$videos = latestVideo();
$allvid= allVideo();
  

 ?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="Créer un bouton de partage personnalisé pour Facebook - karac blog" />
    <meta property="og:image" content="https://karac.ch/storage/articles/August2017/pJBVDQrp5BpNriveaDZg.jpg" />
    <meta property="og:description" content="Dans ce tutoriel, nous allons voir comment ajouter à votre site un joli bouton de partage personnalisé pour Facebook (le fonctionnement est le même pour les autres réseaux sociaux)." />
    <meta property="og:url" content="https://karac.ch/blog/bouton_partage_personnalise">
    <title>Mob blog Houssem</title>
    <link rel="stylesheet" href="../bootstrap.min.css" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../css/normalize.css">
    <link rel="stylesheet" type="text/css" href="../css/article.css">
  </head>
  <body>
    <header>
    
      <nav class="row navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="index.php"><img src="images/logo.png" alt="logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto w-100 d-flex justify-content-around align-items-center text-center">
            <li class="nav-item active">
              <a class="nav-link" href="index.php"><i class="fas fa-home"></i> Acceuil <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="posts.php"><i class="fas fa-book"></i> Tous les articles</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="contact.phtml"><i class="fas fa-phone"></i> Contactez-moi</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="propos.php"><i class="fas fa-user-tie"></i> À propos de moi</a>
              
            </li>
            <li class="nav-item">
              <a class="nav-link" href="login.php"><i class="fas fa-user-cog"></i> Administration</a>
            </li>
          </ul>
        </div>
      </nav>
  </header>
 
    <div class="row">
      <div class="col-md-8"></div>
      <div class="col-md-4 ">
        <form class="form-inline " action="resultat.php" method="POST">
          <input class="form-control col-md-9" type="search" name="title" placeholder="Search" aria-label="Search">
          <button class="btn btn-info col-md-3" type="submit"><i class="fas fa-search"></i> Search</button>
        </form>
      </div>
    </div>
    <hr>
    <div  class="container-fluid">
      <div  style="max-width:1350px; margin:auto;" class="row">
        <div class="col-md-9 shadow-lg p-3 rounded" style="background:url('images/bg.jpg');background-repeat: repeat;background-size: contain; ">
          
              </div>
            </div>
          </div>

              <aside style="border: 10px solid #230F09FF;border-top:none; background:url('images/bg.jpg');background-repeat: repeat;background-size: contain; " class=" col-md-3 shadow-lg p-3 rounded" >
                <div class="col-md-12">
                  <p class=" text-info h3 text-center pt-2 pb-2" style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF;"><b><i class="fas fa-comments"></i> Le plus populaire</b></p>
                  <?php foreach ($popular as $pop): ?>
                  
                  <img style="height: 200px" class="img-thumbnail w-100" src="<?= $pop->image?>" class="card-img-top">
                  <div class="card-body">
                    <h4 class="card-title"><b><i class="fas fa-newspaper"></i> <?= $pop->title?></b></h4>
                    <?php foreach ($user as $value): ?>
                    <p  style="color: grey"><b><i class="fas fa-pen-alt"></i> Publié par:</b> <span style="color: #55AA00FF"><b><?= $value->firstname.' '.$value->lastname ?></b></span></p>
                    <?php  endforeach; ?>
                    <time><span style="color: grey"><i class="fas fa-clock"></i> Le </span><?= $pop->date ?></time>
                    <p  style="color: grey"><b><i class="fas fa-comments"></i> Nombre de commentaires:</b> <span style="color: #55AA00FF"><b><?= $pop->nbrcomments ?></b></span></p>
                    <a href="article.php?id=<?= $pop->id ?>" class="btn btn-primary" ><b>Voir l'article</b></a>
                    <a href="https://www.facebook.com/sharer/sharer.php?u=http://localhost/blog/article.php?id=<?= $pop->id ?>" class="sharebox btn btn-info" target="blank">
                      <span class="fb-icon"></span><b><i class="fab fa-facebook"></b></i> partager</b></a>
                    </div>
                    <?php endforeach ?>
                  </div>
                  <div class="col-md-12">
                    <p class=" text-info h3 text-center pt-2 pb-2" style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF;"><b><i class="fas fa-comments"></i> Le dernier commentaire:</b></p>
                    <?php foreach ($latestcomments as $com): ?>
                    <!--<a class="btn btn-danger btn-sm float-right" href="removeComment.php?id=<?=$com->id?>&article=<?=$article->id?>"><i class="fas fa-trash-alt"></i></a>-->
                    <h4 class="row" style="color: #F75107FF"><i class="fas fa-user-edit"></i> <?= $com->author ?></h4>
                    <p class="h5 row" style="color: #F75107FF">Pour l'article: <?php echo $com->title; ?></p>
                    <time><i class="fas fa-clock"></i> Le <?= $com->date ?></time>
                    <hr>
                    <div class="row">
                      <p class="col-md-12"><i class="fas fa-quote-right"></i> <?= $com->comment ?></p>
                    </div>
                    <div class="text-center">
                      <a class="btn btn-danger mb-2" href="article.php?id=<?= $com->articleId ?>">Voir l'article</a>
                    </div>
                    <?php endforeach; ?>
                  </div>
                  <div class="col-md-12">
                    <p style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF; " class="h3 text-info pt-2 pb-2 text-center"><b>Réseau sociaux</b></p>
                    <div class="row">
                      <a href="https://www.facebook.com/houssem.sahiliano" target="blank"><p style="color: #FF5500FF;font-size: 3em" class="col-md-3 rounded-circle"><i class="fab fa-facebook-square"></i></p></a>
                      <a href="https://www.instagram.com/houssem_mbrr/" target="blank"><p style="color: #FF5500FF;font-size: 3em" class="col-md-3 rounded-circle"><i class="fab fa-instagram"></i></p></a>
                      <p style="color: #FF5500FF;font-size: 3em" class="col-md-3 rounded-circle"><i class="fab fa-twitter-square"></i></p>
                      <a href="https://www.linkedin.com/in/houssem-eddine-mabrouk-619456138/" target="blank"><p style="color: #FF5500FF;font-size: 3em" class="col-md-3 rounded-circle"><i class="fab fa-linkedin"></i></p></a>
                      <a href="https://www.youtube.com/channel/UCOTiomQKUi-Oc1IPnhS0woQ?view_as=subscriber" target="blank"><p style="color: #FF5500FF;font-size: 3em" class="col-md-3 rounded-circle"><i class="fab fa-youtube-square"> </i></p></a>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <p style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF; " class="h3 text-info pt-2 pb-2 text-center"><b><i class="fas fa-bookmark"></i> Catégories</b></p>
                    <?php foreach ($category as $value): ?>
                    <ul class=" pl-2">
                      <li><a class="btn btn-danger w-100" href="getCategory.php?id=<?php echo $value->id?>"><b><?php echo $value->name; ?></b></a></li>
                    </ul>
                    <?php endforeach; ?>
                    
                    
                  </div>
                  <div class="col-md-12 ">
                    <p class=" text-info h3 text-center pt-2 pb-2" style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF;"><b><i class="fas fa-video"></i> Dernière vidéo</b></p>
                    <?php foreach ($videos as $vid): ?>
                    <iframe class="img-thumbnail" width="560" height="315" src="<?php echo $vid->video ?>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <?php endforeach ?>
                  </div>
                  <div class="col-md-12">
                    <p style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF; " class="h3 text-info pt-2 pb-2 text-center "><b><i class="fas fa-cloud"></i> Méteo</b></p>
                    <iframe class="w-100" src="https://www.meteoblue.com/fr/meteo/widget/daily/tunis_tunisie_2464470?geoloc=fixed&days=5&tempunit=CELSIUS&windunit=KILOMETER_PER_HOUR&precipunit=MILLIMETER&coloured=coloured&pictoicon=0&pictoicon=1&maxtemperature=0&maxtemperature=1&mintemperature=0&mintemperature=1&windspeed=0&windspeed=1&windgust=0&winddirection=0&winddirection=1&uv=0&humidity=0&precipitation=0&precipitation=1&precipitationprobability=0&precipitationprobability=1&spot=0&spot=1&pressure=0&layout=light"  frameborder="0" scrolling="NO" allowtransparency="true" sandbox="allow-same-origin allow-scripts allow-popups allow-popups-to-escape-sandbox" style="width: 270px;height: 363px"></iframe>
                  </div>
                  <div class="col-md-12 mt-3">
                    <p class=" text-info h3 text-center pt-2 pb-2" style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF;"><b><i class="fas fa-calendar-week"></i> Calenderier</b></p>
                    <iframe class="col-md-12 pl-5" name="InlineFrame1" id="InlineFrame1" style="width:690px;height:235px;" src="https://www.mathieuweb.fr/calendrier/calendrier-des-semaines.php?nb_mois=1&nb_mois_ligne=4&mois=0&an=0&langue=fr&texte_color=B9CBDD&week_color=DAE9F8&week_end_color=C7DAED&police_color=453413&sel=true" scrolling="no" frameborder="0" allowtransparency="true"></iframe>
                  </div>
                  <div class="col-md-12 ">
                    <p class=" text-info h3 text-center pt-2 pb-2" style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF;"><b><i class="fas fa-user-md"></i> Â Propos</b></p>
                    <img src="images/photo1.jpg " class="w-100 border border-info rounded mb-2">
                    <p style="font-size: 0.8em">Je m'appelle Houssem Eddine Mabrouk, j'ai 28 ans. Je suis un Ingénieur en Génie Hydraulique et un Développeur Web Full-Stack. Grâce à ma formation réalisée à 3W Academy de Tunis, j’ai développé des connaissances en Intégration et Développement WEB qui m’ont conforté dans ma volonté de m’orienter dans le secteur du développement des applications web.
                    </p>
                  </div>
                  <div class="col-md-12 mb-4">
                    <a href="https://houss-mbr.000webhostapp.com/" target="blank">
                      <div  id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                        <div class="carousel-inner">
                          <div class="carousel-item active">
                            <img  style="height: 150px" src="images/port.JPG" class="d-block w-100" alt="...">
                          </div>
                          <div class="carousel-item">
                            <img  style="height: 150px" src="images/s11.jpg" class="d-block w-100" alt="...">
                          </div>
                          <div class="carousel-item">
                            <img  style="height: 150px" src="images/s12.jpg" class="d-block w-100" alt="...">
                          </div>
                          <div class="carousel-item">
                            <img  style="height: 150px" src="images/10.jpg" class="d-block w-100" alt="...">
                          </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="sr-only">Next</span>
                        </a>
                      </div></a>
                    </div>
                    <div class="col-md-12 ">
                      <p class=" text-info h3 text-center pt-2 pb-2" style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF;"><b><i class="fas fa-place-of-worship"></i> Notre locale</b></p>
                      <iframe class="img-thumbnail" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12770.511352168016!2d10.2006248!3d36.8513882!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd820fc66162a8c3c!2s3W+academy!5e0!3m2!1sfr!2stn!4v1555112643693!5m2!1sfr!2stn" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                  </aside>
                </div>
              </div>
              <!--<div class="row">
                <div style="height: 80px" class="col-md-1 bg-dark border border-white"><p class="h4 text-white pt-2 pl-2"><b>Nos vidéos</b></p></div>
                <marquee  style="height: 80px" class=" col-md-11 pt-2 pb-2 text-white bg-dark border border-white d-sm-inline" direction="right">
                <?php foreach ($allvid as $vi): ?>
                <iframe  width="150" height="60" src="<?php echo $vi->video ?>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <?php endforeach ?>
                </marquee>-->
              </div>
              <footer>
                <div class="container-fluid footer ">
                  <div class="row licence">
                    <div class="col-md-12">
                      <h3><i class="far fa-copyright"></i><b>Blog Houssem Eddine Mabrouk 2019</b></h3>
                      <div class="fr">
                        <div style="display: inline-block;">
                          <input class="col-md-6 fEmail" name='Email' placeholder='Entrer ton Email'/>
                          <a href="#" class="subS">S'inscrire</a>
                        </div>
                      </div>
                    </div>
                    <div class="soc col-md-12">
                      <ul>
                        <li class="soc1"><a href="https://www.linkedin.com/in/houssem-eddine-mabrouk-619456138/"target="_blank"></a></li>
                        <li class="soc2"><a href="https://www.facebook.com/houssem.sahiliano"target="_blank"></a></li>
                        <li class="soc3"><a href="https://twitter.com/twitter"target="_blank"></a></li>
                        <li class="soc4"><a href="https://www.instagram.com/houssem_mbrr"target="_blank"></a></li>
                        <li class="soc5"><a href="https://3wa.fr/"target="_blank"></a></li>
                        <li class="soc6"><a href="https://www.youtube.com/channel/UCOTiomQKUi-Oc1IPnhS0woQ?view_as=subscriber"target="_blank"></a></li>
                        <li class="soc7"><a href="mailto:houssemeddinemabrouk@gmail.com"target="_blank"></a></li>
                        <li class="soc8"><a href="https://dribbble.com/Houssem-mbr"target="_blank"></a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="text-right mr-5">
                    <a  id="tp" style="font-size: 3em;color: #FF0E00FF; cursor: pointer;" ><i class="fas fa-arrow-circle-up"></i></a>
                  </div>
                </div>
              </footer>
              <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
              <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
              <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
              <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
              <script>
              $(document).ready(function(){
              // Add smooth scrolling to all links
              $("#tp").on('click', function(event) {
              // Make sure this.hash has a value before overriding default behavior
              if (this.header !== "") {
              // Prevent default anchor click behavior
              event.preventDefault();
              // Store hash
              var header = this.header;
              // Using jQuery's animate() method to add smooth page scroll
              // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
              $('html, body').animate({
              scrollTop: $('header').offset().top
              }, 2000, function(){
              // Add hash (#) to URL when done scrolling (default click behavior)
              window.location.header = header;
              });
              } // End if
              });
              });
              !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
              </script>
            </body>
          </html>