<header class="container-fluid bg-dark">
      <nav class="row navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="index.php"><img src="images/logo.png" alt="logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto w-100 d-flex justify-content-around align-items-center text-center">
            <li class="nav-item active">
              <a class="nav-link" href="index.php"><i class="fas fa-home"></i> Acceuil <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="posts.php"><i class="fas fa-book"></i> Tous les articles</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="contact.phtml"><i class="fas fa-phone"></i> Contactez-moi</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="propos.php"><i class="fas fa-user-tie"></i> À propos de moi</a>
              
            </li>
            <li class="nav-item">
              <a class="nav-link" href="login.php"><i class="fas fa-user-cog"></i> Administration</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>