<aside style="border: 10px solid #230F09FF;border-top:none; background:url('images/bg.jpg');background-repeat: repeat;background-size: contain; " class=" col-md-3 shadow-lg p-3 rounded" >
                <div class="col-md-12">
                  <p class=" text-info h3 text-center pt-2 pb-2" style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF;"><b><i class="fas fa-comments"></i> Le plus populaire</b></p>
                  <?php foreach ($popular as $pop): ?>
                  
                  <img style="height: 200px" class="img-thumbnail w-100" src="<?= $pop->image?>" class="card-img-top">
                  <div class="card-body">
                    <h4 class="card-title"><b><i class="fas fa-newspaper"></i> <?= $pop->title?></b></h4>
                    <?php foreach ($user as $value): ?>
                    <p  style="color: grey"><b><i class="fas fa-pen-alt"></i> Publié par:</b> <span style="color: #55AA00FF"><b><?= $value->firstname.' '.$value->lastname ?></b></span></p>
                    <?php  endforeach; ?>
                    <time><span style="color: grey"><i class="fas fa-clock"></i> Le </span><?= $pop->date ?></time>
                    <p  style="color: grey"><b><i class="fas fa-comments"></i> Nombre de commentaires:</b> <span style="color: #55AA00FF"><b><?= $pop->nbrcomments ?></b></span></p>
                    <a href="article.php?id=<?= $pop->id ?>" class="btn btn-primary" ><b>Voir l'article</b></a>
                    <a href="https://www.facebook.com/sharer/sharer.php?u=http://localhost/blog/article.php?id=<?= $pop->id ?>" class="sharebox btn btn-info" target="blank">
                      <span class="fb-icon"></span><b><i class="fab fa-facebook"></b></i> partager</b></a>
                    </div>
                    <?php endforeach ?>
                  </div>
                  <div class="col-md-12">
                    <p class=" text-info h3 text-center pt-2 pb-2" style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF;"><b><i class="fas fa-comments"></i> Le dernier commentaire:</b></p>
                    <?php foreach ($latestcomments as $com): ?>
                    <!--<a class="btn btn-danger btn-sm float-right" href="removeComment.php?id=<?=$com->id?>&article=<?=$article->id?>"><i class="fas fa-trash-alt"></i></a>-->
                    <h4 class="row" style="color: #F75107FF"><i class="fas fa-user-edit"></i> <?= $com->author ?></h4>
                    <p class="h5 row" style="color: #F75107FF">Pour l'article: <?php echo $com->title; ?></p>
                    <time><i class="fas fa-clock"></i> Le <?= $com->date ?></time>
                    <hr>
                    <div class="row">
                      <p class="col-md-12"><i class="fas fa-quote-right"></i> <?= $com->comment ?></p>
                    </div>
                    <div class="text-center">
                      <a class="btn btn-danger mb-2" href="article.php?id=<?= $com->articleId ?>">Voir l'article</a>
                    </div>
                    <?php endforeach; ?>
                  </div>
                  <div class="col-md-12">
                    <p style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF; " class="h3 text-info pt-2 pb-2 text-center"><b>Réseau sociaux</b></p>
                    <div class="row">
                      <a href="https://www.facebook.com/houssem.sahiliano" target="blank"><p style="color: #FF5500FF;font-size: 3em" class="col-md-3 rounded-circle"><i class="fab fa-facebook-square"></i></p></a>
                      <a href="https://www.instagram.com/houssem_mbrr/" target="blank"><p style="color: #FF5500FF;font-size: 3em" class="col-md-3 rounded-circle"><i class="fab fa-instagram"></i></p></a>
                      <p style="color: #FF5500FF;font-size: 3em" class="col-md-3 rounded-circle"><i class="fab fa-twitter-square"></i></p>
                      <a href="https://www.linkedin.com/in/houssem-eddine-mabrouk-619456138/" target="blank"><p style="color: #FF5500FF;font-size: 3em" class="col-md-3 rounded-circle"><i class="fab fa-linkedin"></i></p></a>
                      <a href="https://www.youtube.com/channel/UCOTiomQKUi-Oc1IPnhS0woQ?view_as=subscriber" target="blank"><p style="color: #FF5500FF;font-size: 3em" class="col-md-3 rounded-circle"><i class="fab fa-youtube-square"> </i></p></a>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <p style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF; " class="h3 text-info pt-2 pb-2 text-center"><b><i class="fas fa-bookmark"></i> Catégories</b></p>
                    <?php foreach ($categorynbr as $value): ?>
                    <ul class=" pl-2">
                      <li><a class="btn btn-info w-100" href="getCategory.php?id=<?php echo $value->id?>"><b><?php echo $value->name; ?> <span class="text-white float-right"><?php echo $value->n; ?></span></b></a></li>
                    </ul> 
                    <?php endforeach; ?>
                    
                    
                  </div>
                  <div class="col-md-12 ">
                    <p class=" text-info h3 text-center pt-2 pb-2" style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF;"><b><i class="fas fa-video"></i> Dernière vidéo</b></p>
                    <?php foreach ($videos as $vid): ?>
                    <iframe class="img-thumbnail" width="560" height="315" src="<?php echo $vid->video ?>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <?php endforeach ?>
                  </div>
                  <div class="col-md-12">
                    <p style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF; " class="h3 text-info pt-2 pb-2 text-center "><b><i class="fas fa-cloud"></i> Méteo</b></p>
                    <iframe class="w-100" src="https://www.meteoblue.com/fr/meteo/widget/daily/tunis_tunisie_2464470?geoloc=fixed&days=5&tempunit=CELSIUS&windunit=KILOMETER_PER_HOUR&precipunit=MILLIMETER&coloured=coloured&pictoicon=0&pictoicon=1&maxtemperature=0&maxtemperature=1&mintemperature=0&mintemperature=1&windspeed=0&windspeed=1&windgust=0&winddirection=0&winddirection=1&uv=0&humidity=0&precipitation=0&precipitation=1&precipitationprobability=0&precipitationprobability=1&spot=0&spot=1&pressure=0&layout=light"  frameborder="0" scrolling="NO" allowtransparency="true" sandbox="allow-same-origin allow-scripts allow-popups allow-popups-to-escape-sandbox" style="width: 270px;height: 363px"></iframe>
                  </div>
                  <div class="col-md-12 mt-3">
                    <p class=" text-info h3 text-center pt-2 pb-2" style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF;"><b><i class="fas fa-calendar-week"></i> Calenderier</b></p>
                    <iframe class="col-md-12 pl-5" name="InlineFrame1" id="InlineFrame1" style="width:690px;height:235px;" src="https://www.mathieuweb.fr/calendrier/calendrier-des-semaines.php?nb_mois=1&nb_mois_ligne=4&mois=0&an=0&langue=fr&texte_color=B9CBDD&week_color=DAE9F8&week_end_color=C7DAED&police_color=453413&sel=true" scrolling="no" frameborder="0" allowtransparency="true"></iframe>
                  </div>
                  <div class="col-md-12 ">
                    <p class=" text-info h3 text-center pt-2 pb-2" style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF;"><b><i class="fas fa-user-md"></i> Â Propos</b></p>
                    <img src="images/photo1.jpg " class="w-100 border border-info rounded mb-2">
                    <p style="font-size: 0.8em">Je m'appelle Houssem Eddine Mabrouk, j'ai 28 ans. Je suis un Ingénieur en Génie Hydraulique et un Développeur Web Full-Stack. Grâce à ma formation réalisée à 3W Academy de Tunis, j’ai développé des connaissances en Intégration et Développement WEB qui m’ont conforté dans ma volonté de m’orienter dans le secteur du développement des applications web.
                    </p>
                  </div>
                  <div class="col-md-12 mb-4">
                    <a href="https://houss-mbr.000webhostapp.com/" target="blank">
                      <div  id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                        <div class="carousel-inner">
                          <div class="carousel-item active">
                            <img  style="height: 150px" src="images/port.JPG" class="d-block w-100" alt="...">
                          </div>
                          <div class="carousel-item">
                            <img  style="height: 150px" src="images/s11.jpg" class="d-block w-100" alt="...">
                          </div>
                          <div class="carousel-item">
                            <img  style="height: 150px" src="images/s12.jpg" class="d-block w-100" alt="...">
                          </div>
                          <div class="carousel-item">
                            <img  style="height: 150px" src="images/10.jpg" class="d-block w-100" alt="...">
                          </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="sr-only">Next</span>
                        </a>
                      </div></a>
                    </div>
                    <div class="col-md-12 ">
                      <p class=" text-info h3 text-center pt-2 pb-2" style="border-top:3px solid #00AAFFFF; border-bottom:3px solid #00AAFFFF;"><b><i class="fas fa-place-of-worship"></i> Notre locale</b></p>
                      <iframe class="img-thumbnail" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12770.511352168016!2d10.2006248!3d36.8513882!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd820fc66162a8c3c!2s3W+academy!5e0!3m2!1sfr!2stn!4v1555112643693!5m2!1sfr!2stn" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                  </aside>